name: 3Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3530466
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 3Dscanning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0C1F06'
    - '#B58F6D'
    - '#6F99E0'
    - '#F20C27'
    - '#FFFFFB'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
